#!/bin/bash

: ${BACULA_DEBUG:="50"}
: ${BACULA_DBHOST:="bacula"}
: ${BACULA_DBNAME:="bacula-db"}
: ${BACULA_DBUSER:="bacula"}
: ${BACULA_DBPASSWORD:="bacula"}
: ${BACULA_DIRNAME:="bacula"}
: ${BACULA_CONSOLEPASSWORD:="password"}
: ${BACULA_FDNAME:="bacula-fd"}
: ${BACULA_DIRADDRESS:="127.0.0.1"}
: ${BACULA_SDADDRESS:="127.0.0.1"}

echo "=> Checking wether database service at ${BACULA_DBHOST} is up"
while true; do ping -c1 ${BACULA_DBHOST} > /dev/null && break; done
echo "=> Succeeded"

for d in $(seq 10 -1 1); do
 echo "=> Waiting ${d}s for the database service to start"
 sleep 1
done

echo "${BACULA_DBHOST}:*:*:${BACULA_DBUSER}:${DB_PASSWORD}" > /root/.pgpass
chmod 0600 /root/.pgpass

echo "=> Attempting database setup"
if psql -h ${BACULA_DBHOST} -U ${BACULA_DBUSER} -lqt | cut -d\| -f1 | grep -qw ${BACULA_DBNAME}; then
 echo "=> Database already setup; skipping."
else 
 echo "=> Setting Database ..."
fi

CONFIGS_VARS=(
 BACULA_DBHOST
 BACULA_DBNAME
 BACULA_DBUSER
 BACULA_DBPASSWORD
 BACULA_DIRNAME
 BACULA_CONSOLEPASSWORD
 BACULA_FDNAME
 BACULA_DIRADDRESS
 BACULA_SDADDRESS
 )

echo "=> Setting Bacula Director ..."
for c in ${CONFIGS_VARS[@]}; do
 sed -i "s,@@${c}@@,$(eval echo \$${c})," /etc/bacula/bacula-dir.conf
 sed -i "s,@@${c}@@,$(eval echo \$${c})," /etc/bacula/bconsole.conf
done
