#!/bin/bash

: ${BACULA_DEBUG:="50"}
: ${BACULA_DBHOST:="bacula"}
: ${BACULA_DBNAME:="bacula-db"}
: ${BACULA_DBUSER:="bacula"}
: ${BACULA_DBPASSWORD:="bacula"}
: ${BACULA_DIRNAME:="bacula"}
: ${BACULA_CONSOLEPASSWORD:="password"}
: ${BACULA_FDNAME:="bacula-fd"}
: ${BACULA_DIRADDRESS:="127.0.0.1"}
: ${BACULA_SDADDRESS:="127.0.0.1"}

echo "=> Checking wether database service at ${BACULA_DBHOST} is up"
if ping -c1 ${BACULA_DBHOST} > /dev/null; then
 echo "=> Succeeded, Database up ..."
else
 echo "=> Database down, exiting"
 exit 1
fi 

for i in $(seq 10 -1 1)
do
 echo "=> Waiting database configuration ${i} ..."
 sleep 1
done

echo "${BACULA_DBHOST}:*:*:${BACULA_DBUSER}:${BACULA_DBPASSWORD}" >> ~/.pgpass
echo "${BACULA_DBHOST}:*:*:postgres:${BACULA_DBPASSWORD}" >> ~/.pgpass
chmod 0600 ~/.pgpass

echo "=> Creating user ${BACULA_DBUSER}"
psql -h ${BACULA_DBHOST} -U postgres -c "CREATE USER ${BACULA_DBUSER} WITH ENCRYPTED PASSWORD '${BACULA_DBPASSWORD}'"

echo "=> Attempting database setup"
if psql -h ${BACULA_DBHOST} -U ${BACULA_DBUSER} -lqt | cut -d\| -f1 | grep -w ${BACULA_DBNAME}; then
 echo "=> Database already setup, skipping."
else 
 echo "=> Setting Database ..."
 db_name=${BACULA_DBNAME}
 /etc/bacula/scripts/create_postgresql_database -h ${BACULA_DBHOST} -U postgres
 /etc/bacula/scripts/make_postgresql_tables -h ${BACULA_DBHOST} -U postgres
 /etc/bacula/scripts/grant_postgresql_privileges -h ${BACULA_DBHOST} -U postgres
 unset db_name
fi

CONFIGS_VARS=(
 BACULA_DBHOST
 BACULA_DBNAME
 BACULA_DBUSER
 BACULA_DBPASSWORD
 BACULA_DIRNAME
 BACULA_CONSOLEPASSWORD
 BACULA_FDNAME
 BACULA_DIRADDRESS
 BACULA_SDADDRESS
 )

echo "=> Setting Bacula Director ..."
for c in ${CONFIGS_VARS[@]}; do
 sed -i "s,@@${c}@@,$(eval echo \$${c})," /etc/bacula/bacula-dir.conf
 sed -i "s,@@${c}@@,$(eval echo \$${c})," /etc/bacula/bconsole.conf
done
